### PR TITLE
:art: dockerify.

### PR DESCRIPTION
**Pull request by cdaringe**
# problem statement
- gotta love docker!
# solution
- provide basic Dockerfile & instructions

### CODE REVIEW

**Comment by kkemple** [comment]
thanks for the pull request, also a big fan of docker, will look this over!

**Comment by cdaringe** [comment]
any motion on this?  thanks!

**Comment by travi** [comment]
You may have seen that I've been working to pull the [hapi plugin](https://github.com/greenkeeper-keeper/hapi-greenkeeper-keeper) out to be consumable separately. 

As part of that, I'd like to document the various options for deploying here: https://github.com/greenkeeper-keeper/meta

Do you see anything about that effort, including the changes in [my PR](https://github.com/kkemple/greenkeeper-keeper/pull/50) to this project, that would complicate your intentions with your PR?

**Comment by cdaringe** [comment]
- rebased, dropped the .gitignore content

> ...complicate your intentions with your PR

- no sir!  this little guy will still work fine.  previously i was copying specific dirs, like `plugins/` but i simplified it.  it would work fine w/ your changes

**Comment by travi** [comment]
sounds great. 

i ended up merging my updates to use the hapi plugin into master. would you mind verifying your changes with the latest master just to confirm? assuming things are good, i should be able to get the changes merged shortly after you re-verify.

thanks!

**Comment by travi** [comment]
since you already have the image published to docker hub, i linked to it as a deployment option: https://github.com/greenkeeper-keeper/meta#instance-deployment-options

**Comment by cdaringe** [comment]
sure thing.  i may not get to it for a bit, but this week i intend to do a build.  i'll test it and update the image onsuccess

**Comment by cdaringe** [comment]
rebuilt, tested, and image updated on docker hub!

**Comment by cdaringe** [comment]
only 83Mb too.  pretty small overall

**Comment by travi** [comment]
awesome. thanks for the contribution and the additional testing with the other changes happening.

**Comment by cdaringe** [comment]
🎉

**Pull request merged**
