### PR TITLE
accept PRs from the integration url as official greenkeeper PRs

### PR DESCRIPTION
**Pull request by travi**
I have deployed this branch to heroku to confirm behavior to see if this fixes greenkeeper-keeper with the new integration. However, I haven't had any greenkeeper PRs come through yet, so I can't say for sure yet. I will follow up once I know more confidently.

### CODE REVIEW

**Comment by travi** [comment]
it looks like the problem goes beyond just a new sender. `action` comes through from `request.payload` as `undefined` for PRs from the new greenkeeper integration, so that is also causing it not to match.

**Comment by travi** [comment]
i was wrong about the `action` coming through as `undefined`. it looks like that was from webhooks that were not PRs that I had misconfigured. 

i think i'm getting closer. i initially had the integration's `sender` url wrong (had `greenkeeperio` instead of `greenkeeper`), so i hope things will get further with that fixed.

**Comment by travi** [comment]
It looks like that did the trick. Had a few PRs get merged successfully this morning, like https://github.com/travi/admin.travi.org-components/pull/214.

I'll get the logging cleaned up and then I think this should be good to merge.

**Comment by travi** [comment]
updated

**Comment by travi** [comment]
@kkemple ?

**Comment by kkemple** [comment]
so sorry for the delay on this

**Pull request merged**
